name = "TransformersDownloads"
uuid = "83ccf3dd-bfab-49d6-97f1-f49acc47b240"
authors = ["AbrJA <abraham.jaimes.mx@gmail.com>"]
version = "0.1.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
HuggingFaceApi = "3cc741c3-0c9d-4fbe-84fa-cdec264173de"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Mmap = "a63ad114-7e13-5084-954f-fe012c677804"
SafeTensors = "eeda0dda-7046-4914-a807-2495fc7abb89"

[weakdeps]
Pickle = "fbb45041-c46e-462f-888f-7c521cafbc2c"

[extensions]
TransformersDownloadsPickleExt = "Pickle"

[compat]
julia = "1"
HuggingFaceApi = "0.1"
JSON = "1"
Mmap = "1"
Pickle = "0.3"
SafeTensors = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Pickle = "fbb45041-c46e-462f-888f-7c521cafbc2c"

[targets]
test = ["Test", "Pickle"]
